name: xai_proj_t2
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2024.1
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - datasets==3.6.0
      - dill==0.3.8
      - filelock==3.18.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - huggingface-hub==0.31.4
      - idna==3.10
      - multidict==6.4.4
      - multiprocess==0.70.16
      - propcache==0.3.1
      - pyarrow==20.0.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - urllib3==2.4.0
      - xxhash==3.5.0
      - yarl==1.20.0
